# Generated by Django 3.2.5 on 2021-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_bookcategory_booklocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='booklocation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
