# Generated by Django 3.2.5 on 2021-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210801_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='booklocation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
