# Generated by Django 3.2.5 on 2021-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210801_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booklocation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
