# Generated by Django 3.2.5 on 2021-08-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210801_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
