from django.urls import path
from .views import (UserView,
                    BookDetailView,
                    BookCategoryView,
                    BookCategoryDetailView,
                    BookCategoryCreateView,
                    BookCategoryUpdateView,
                    BookCategoryDeleteView,
                    BookLocationView,
                    BookLocationCreateView,
                    BookLocationUpdateView,
                    BookLocationDeleteView,
                    BookView,
                    BookCreateView,
                    BookUpdateView,
                    BookDeleteView,
                    )

urlpatterns = [
    path('users', UserView.as_view()),
    path('books', BookView.as_view()),
    path('books-create', BookCreateView.as_view()),
    path('books/<pk>', BookDetailView.as_view()),
    path('books/<pk>/update', BookUpdateView.as_view()),
    path('books/<pk>/delete', BookDeleteView.as_view()),
    path('book-location', BookLocationView.as_view()),
    path('book-location-create', BookLocationCreateView.as_view()),
    path('book-location/<pk>/update', BookLocationUpdateView.as_view()),
    path('book-location/<pk>/delete', BookLocationDeleteView.as_view()),
    path('book-category', BookCategoryView.as_view()),
    path('book-category-create', BookCategoryCreateView.as_view()),
    path('book-category/<pk>', BookCategoryDetailView.as_view()),
    path('book-category/<pk>/update', BookCategoryUpdateView.as_view()),
    path('book-category/<pk>/delete', BookCategoryDeleteView.as_view()),
]
